version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependabot
  versioning-strategy: increase
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: mime-types
    versions:
    - 2.1.29
  - dependency-name: is-core-module
    versions:
    - 2.2.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: is-arguments
    versions:
    - 1.1.0
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependabot
  versioning-strategy: increase
